	.align 2
DirectSoundWaveData_08B5B234::
	.incbin "sound/direct_sound_samples/08B5B234.bin"

	.align 2
DirectSoundWaveData_08B5BE9C::
	.incbin "sound/direct_sound_samples/08B5BE9C.bin"

	.align 2
DirectSoundWaveData_08B5C910::
	.incbin "sound/direct_sound_samples/08B5C910.bin"

	.align 2
DirectSoundWaveData_08B5DAAC::
	.incbin "sound/direct_sound_samples/08B5DAAC.bin"

	.align 2
DirectSoundWaveData_08B5EE10::
	.incbin "sound/direct_sound_samples/08B5EE10.bin"

	.align 2
DirectSoundWaveData_08B624E0::
	.incbin "sound/direct_sound_samples/08B624E0.bin"

	.align 2
DirectSoundWaveData_08B66B74::
	.incbin "sound/direct_sound_samples/08B66B74.bin"

	.align 2
DirectSoundWaveData_08B69238::
	.incbin "sound/direct_sound_samples/08B69238.bin"

	.align 2
DirectSoundWaveData_08B6BBE8::
	.incbin "sound/direct_sound_samples/08B6BBE8.bin"

	.align 2
DirectSoundWaveData_08B6D704::
	.incbin "sound/direct_sound_samples/08B6D704.bin"

	.align 2
DirectSoundWaveData_08B704C8::
	.incbin "sound/direct_sound_samples/08B704C8.bin"

	.align 2
DirectSoundWaveData_08B73FC0::
	.incbin "sound/direct_sound_samples/08B73FC0.bin"

	.align 2
DirectSoundWaveData_08B7533C::
	.incbin "sound/direct_sound_samples/08B7533C.bin"

	.align 2
DirectSoundWaveData_08B78118::
	.incbin "sound/direct_sound_samples/08B78118.bin"

	.align 2
DirectSoundWaveData_08B78B2C::
	.incbin "sound/direct_sound_samples/08B78B2C.bin"

	.align 2
DirectSoundWaveData_08B79D9C::
	.incbin "sound/direct_sound_samples/08B79D9C.bin"

	.align 2
DirectSoundWaveData_08B7D55C::
	.incbin "sound/direct_sound_samples/08B7D55C.bin"

	.align 2
DirectSoundWaveData_08B809E8::
	.incbin "sound/direct_sound_samples/08B809E8.bin"

	.align 2
DirectSoundWaveData_08B836E4::
	.incbin "sound/direct_sound_samples/08B836E4.bin"

	.align 2
DirectSoundWaveData_08B85530::
	.incbin "sound/direct_sound_samples/08B85530.bin"

	.align 2
DirectSoundWaveData_08B86134::
	.incbin "sound/direct_sound_samples/08B86134.bin"

	.align 2
DirectSoundWaveData_08B8A684::
	.incbin "sound/direct_sound_samples/08B8A684.bin"

	.align 2
DirectSoundWaveData_08B8E6AC::
	.incbin "sound/direct_sound_samples/08B8E6AC.bin"

	.align 2
DirectSoundWaveData_08B90CF8::
	.incbin "sound/direct_sound_samples/08B90CF8.bin"

	.align 2
DirectSoundWaveData_08B924A0::
	.incbin "sound/direct_sound_samples/08B924A0.bin"

	.align 2
DirectSoundWaveData_08B94CD0::
	.incbin "sound/direct_sound_samples/08B94CD0.bin"

	.align 2
DirectSoundWaveData_08B9679C::
	.incbin "sound/direct_sound_samples/08B9679C.bin"

	.align 2
DirectSoundWaveData_08B97EA0::
	.incbin "sound/direct_sound_samples/08B97EA0.bin"

	.align 2
DirectSoundWaveData_08B9AF1C::
	.incbin "sound/direct_sound_samples/08B9AF1C.bin"

	.align 2
DirectSoundWaveData_08B9D85C::
	.incbin "sound/direct_sound_samples/08B9D85C.bin"

	.align 2
DirectSoundWaveData_08B9DCD8::
	.incbin "sound/direct_sound_samples/08B9DCD8.bin"

	.align 2
DirectSoundWaveData_08BA12C0::
	.incbin "sound/direct_sound_samples/08BA12C0.bin"

	.align 2
DirectSoundWaveData_08BA3DEC::
	.incbin "sound/direct_sound_samples/08BA3DEC.bin"

	.align 2
DirectSoundWaveData_08BA6DB4::
	.incbin "sound/direct_sound_samples/08BA6DB4.bin"

	.align 2
DirectSoundWaveData_08BA87E8::
	.incbin "sound/direct_sound_samples/08BA87E8.bin"

	.align 2
DirectSoundWaveData_08BAA1BC::
	.incbin "sound/direct_sound_samples/08BAA1BC.bin"

	.align 2
DirectSoundWaveData_08BAB810::
	.incbin "sound/direct_sound_samples/08BAB810.bin"

	.align 2
DirectSoundWaveData_08BACC9C::
	.incbin "sound/direct_sound_samples/08BACC9C.bin"

	.align 2
DirectSoundWaveData_08BAFA60::
	.incbin "sound/direct_sound_samples/08BAFA60.bin"

	.align 2
DirectSoundWaveData_08BB09B8::
	.incbin "sound/direct_sound_samples/08BB09B8.bin"

	.align 2
DirectSoundWaveData_08BB13B4::
	.incbin "sound/direct_sound_samples/08BB13B4.bin"

	.align 2
DirectSoundWaveData_08BB1750::
	.incbin "sound/direct_sound_samples/08BB1750.bin"

	.align 2
DirectSoundWaveData_08BB4930::
	.incbin "sound/direct_sound_samples/08BB4930.bin"

	.align 2
DirectSoundWaveData_08BB5B1C::
	.incbin "sound/direct_sound_samples/08BB5B1C.bin"

	.align 2
DirectSoundWaveData_08BBA11C::
	.incbin "sound/direct_sound_samples/08BBA11C.bin"

	.align 2
DirectSoundWaveData_08BBC474::
	.incbin "sound/direct_sound_samples/08BBC474.bin"

	.align 2
DirectSoundWaveData_08BBEE68::
	.incbin "sound/direct_sound_samples/08BBEE68.bin"

	.align 2
DirectSoundWaveData_08BC2C58::
	.incbin "sound/direct_sound_samples/08BC2C58.bin"

	.align 2
DirectSoundWaveData_08BC5A1C::
	.incbin "sound/direct_sound_samples/08BC5A1C.bin"

	.align 2
DirectSoundWaveData_08BC5AC0::
	.incbin "sound/direct_sound_samples/08BC5AC0.bin"

	.align 2
DirectSoundWaveData_08BC7BC8::
	.incbin "sound/direct_sound_samples/08BC7BC8.bin"

	.align 2
DirectSoundWaveData_08BCB7A8::
	.incbin "sound/direct_sound_samples/08BCB7A8.bin"

	.align 2
DirectSoundWaveData_08BCCE88::
	.incbin "sound/direct_sound_samples/08BCCE88.bin"

	.align 2
DirectSoundWaveData_08BD3408::
	.incbin "sound/direct_sound_samples/08BD3408.bin"

	.align 2
DirectSoundWaveData_08BD9A68::
	.incbin "sound/direct_sound_samples/08BD9A68.bin"

	.align 2
DirectSoundWaveData_08BDFA5C::
	.incbin "sound/direct_sound_samples/08BDFA5C.bin"

	.align 2
DirectSoundWaveData_08BE5F34::
	.incbin "sound/direct_sound_samples/08BE5F34.bin"

	.align 2
DirectSoundWaveData_08BECA00::
	.incbin "sound/direct_sound_samples/08BECA00.bin"

	.align 2
DirectSoundWaveData_08BF2FB4::
	.incbin "sound/direct_sound_samples/08BF2FB4.bin"

	.align 2
DirectSoundWaveData_08BF4434::
	.incbin "sound/direct_sound_samples/08BF4434.bin"

	.align 2
DirectSoundWaveData_08BF6110::
	.incbin "sound/direct_sound_samples/08BF6110.bin"

	.align 2
DirectSoundWaveData_08BF764C::
	.incbin "sound/direct_sound_samples/08BF764C.bin"

	.align 2
DirectSoundWaveData_08BF886C::
	.incbin "sound/direct_sound_samples/08BF886C.bin"

	.align 2
DirectSoundWaveData_08BF9EBC::
	.incbin "sound/direct_sound_samples/08BF9EBC.bin"

	.align 2
DirectSoundWaveData_08BFA240::
	.incbin "sound/direct_sound_samples/08BFA240.bin"

	.align 2
DirectSoundWaveData_08BFD8D8::
	.incbin "sound/direct_sound_samples/08BFD8D8.bin"

	.align 2
DirectSoundWaveData_08C020A4::
	.incbin "sound/direct_sound_samples/08C020A4.bin"

	.align 2
DirectSoundWaveData_08C03F48::
	.incbin "sound/direct_sound_samples/08C03F48.bin"

	.align 2
DirectSoundWaveData_08C07BBC::
	.incbin "sound/direct_sound_samples/08C07BBC.bin"

	.align 2
DirectSoundWaveData_08C0E430::
	.incbin "sound/direct_sound_samples/08C0E430.bin"

	.align 2
DirectSoundWaveData_08C104A4::
	.incbin "sound/direct_sound_samples/08C104A4.bin"

	.align 2
DirectSoundWaveData_08C1263C::
	.incbin "sound/direct_sound_samples/08C1263C.bin"

	.align 2
DirectSoundWaveData_08C17914::
	.incbin "sound/direct_sound_samples/08C17914.bin"

	.align 2
DirectSoundWaveData_08C1D8AC::
	.incbin "sound/direct_sound_samples/08C1D8AC.bin"

	.align 2
DirectSoundWaveData_08C21948::
	.incbin "sound/direct_sound_samples/08C21948.bin"

	.align 2
DirectSoundWaveData_08C28328::
	.incbin "sound/direct_sound_samples/08C28328.bin"

	.align 2
DirectSoundWaveData_08C2C778::
	.incbin "sound/direct_sound_samples/08C2C778.bin"

	.align 2
DirectSoundWaveData_08C2D718::
	.incbin "sound/direct_sound_samples/08C2D718.bin"

	.align 2
DirectSoundWaveData_08C2FAD8::
	.incbin "sound/direct_sound_samples/08C2FAD8.bin"

	.align 2
DirectSoundWaveData_08C365B8::
	.incbin "sound/direct_sound_samples/08C365B8.bin"

	.align 2
DirectSoundWaveData_08C3701C::
	.incbin "sound/direct_sound_samples/08C3701C.bin"

	.align 2
DirectSoundWaveData_08C379E8::
	.incbin "sound/direct_sound_samples/08C379E8.bin"

	.align 2
DirectSoundWaveData_08C38394::
	.incbin "sound/direct_sound_samples/08C38394.bin"

	.align 2
DirectSoundWaveData_08C39C14::
	.incbin "sound/direct_sound_samples/08C39C14.bin"

	.align 2
DirectSoundWaveData_08C3D0F0::
	.incbin "sound/direct_sound_samples/08C3D0F0.bin"

	.align 2
DirectSoundWaveData_08C3D8E8::
	.incbin "sound/direct_sound_samples/08C3D8E8.bin"

	.align 2
DirectSoundWaveData_08C40374::
	.incbin "sound/direct_sound_samples/08C40374.bin"

	.align 2
DirectSoundWaveData_08C4184C::
	.incbin "sound/direct_sound_samples/08C4184C.bin"

	.align 2
DirectSoundWaveData_08C427D0::
	.incbin "sound/direct_sound_samples/08C427D0.bin"

	.align 2
DirectSoundWaveData_08C42C04::
	.incbin "sound/direct_sound_samples/08C42C04.bin"

	.align 2
DirectSoundWaveData_08C430F0::
	.incbin "sound/direct_sound_samples/08C430F0.bin"

	.align 2
DirectSoundWaveData_08C437E0::
	.incbin "sound/direct_sound_samples/08C437E0.bin"

	.align 2
DirectSoundWaveData_08C4551C::
	.incbin "sound/direct_sound_samples/08C4551C.bin"

	.align 2
DirectSoundWaveData_08C472A8::
	.incbin "sound/direct_sound_samples/08C472A8.bin"

	.align 2
DirectSoundWaveData_08C47714::
	.incbin "sound/direct_sound_samples/08C47714.bin"

	.align 2
DirectSoundWaveData_08C49E40::
	.incbin "sound/direct_sound_samples/08C49E40.bin"

	.align 2
DirectSoundWaveData_08C4D530::
	.incbin "sound/direct_sound_samples/08C4D530.bin"

	.align 2
DirectSoundWaveData_08C4E1C8::
	.incbin "sound/direct_sound_samples/08C4E1C8.bin"

	.align 2
DirectSoundWaveData_08C4F53C::
	.incbin "sound/direct_sound_samples/08C4F53C.bin"

	.align 2
DirectSoundWaveData_08C4FAFC::
	.incbin "sound/direct_sound_samples/08C4FAFC.bin"

	.align 2
DirectSoundWaveData_08C50398::
	.incbin "sound/direct_sound_samples/08C50398.bin"

	.align 2
DirectSoundWaveData_08C52B04::
	.incbin "sound/direct_sound_samples/08C52B04.bin"

	.align 2
DirectSoundWaveData_08C54358::
	.incbin "sound/direct_sound_samples/08C54358.bin"

	.align 2
DirectSoundWaveData_08C567E4::
	.incbin "sound/direct_sound_samples/08C567E4.bin"

	.align 2
DirectSoundWaveData_08C58214::
	.incbin "sound/direct_sound_samples/08C58214.bin"

	.align 2
DirectSoundWaveData_08C5980C::
	.incbin "sound/direct_sound_samples/08C5980C.bin"

	.align 2
DirectSoundWaveData_08C5A520::
	.incbin "sound/direct_sound_samples/08C5A520.bin"

	.align 2
DirectSoundWaveData_08C5AF78::
	.incbin "sound/direct_sound_samples/08C5AF78.bin"

	.align 2
DirectSoundWaveData_08C5E148::
	.incbin "sound/direct_sound_samples/08C5E148.bin"

	.align 2
DirectSoundWaveData_08C600EC::
	.incbin "sound/direct_sound_samples/08C600EC.bin"

	.align 2
DirectSoundWaveData_08C642F4::
	.incbin "sound/direct_sound_samples/08C642F4.bin"

	.align 2
DirectSoundWaveData_08C65E14::
	.incbin "sound/direct_sound_samples/08C65E14.bin"

	.align 2
DirectSoundWaveData_08C68A4C::
	.incbin "sound/direct_sound_samples/08C68A4C.bin"

	.align 2
DirectSoundWaveData_08C6A0BC::
	.incbin "sound/direct_sound_samples/08C6A0BC.bin"

	.align 2
DirectSoundWaveData_08C6BD9C::
	.incbin "sound/direct_sound_samples/08C6BD9C.bin"

	.align 2
DirectSoundWaveData_08C6C3E8::
	.incbin "sound/direct_sound_samples/08C6C3E8.bin"

	.align 2
DirectSoundWaveData_08C6F2D8::
	.incbin "sound/direct_sound_samples/08C6F2D8.bin"

	.align 2
DirectSoundWaveData_08C706E4::
	.incbin "sound/direct_sound_samples/08C706E4.bin"

	.align 2
DirectSoundWaveData_08C739A4::
	.incbin "sound/direct_sound_samples/08C739A4.bin"

	.align 2
DirectSoundWaveData_08C74454::
	.incbin "sound/direct_sound_samples/08C74454.bin"

	.align 2
DirectSoundWaveData_08C7663C::
	.incbin "sound/direct_sound_samples/08C7663C.bin"

	.align 2
DirectSoundWaveData_08C78DE0::
	.incbin "sound/direct_sound_samples/08C78DE0.bin"

	.align 2
DirectSoundWaveData_08C7CFC0::
	.incbin "sound/direct_sound_samples/08C7CFC0.bin"

	.align 2
DirectSoundWaveData_08C7DAE4::
	.incbin "sound/direct_sound_samples/08C7DAE4.bin"

	.align 2
DirectSoundWaveData_08C7E954::
	.incbin "sound/direct_sound_samples/08C7E954.bin"

	.align 2
DirectSoundWaveData_08C7FA34::
	.incbin "sound/direct_sound_samples/08C7FA34.bin"

	.align 2
DirectSoundWaveData_08C820AC::
	.incbin "sound/direct_sound_samples/08C820AC.bin"

	.align 2
DirectSoundWaveData_08C84840::
	.incbin "sound/direct_sound_samples/08C84840.bin"

	.align 2
DirectSoundWaveData_08C85250::
	.incbin "sound/direct_sound_samples/08C85250.bin"

	.align 2
DirectSoundWaveData_08C87CDC::
	.incbin "sound/direct_sound_samples/08C87CDC.bin"

	.align 2
DirectSoundWaveData_08C8B098::
	.incbin "sound/direct_sound_samples/08C8B098.bin"

	.align 2
DirectSoundWaveData_08C8B810::
	.incbin "sound/direct_sound_samples/08C8B810.bin"

	.align 2
DirectSoundWaveData_08C8C418::
	.incbin "sound/direct_sound_samples/08C8C418.bin"

	.align 2
DirectSoundWaveData_08C8CD48::
	.incbin "sound/direct_sound_samples/08C8CD48.bin"

	.align 2
DirectSoundWaveData_08C8FC10::
	.incbin "sound/direct_sound_samples/08C8FC10.bin"

	.align 2
DirectSoundWaveData_08C9263C::
	.incbin "sound/direct_sound_samples/08C9263C.bin"

	.align 2
DirectSoundWaveData_08C9480C::
	.incbin "sound/direct_sound_samples/08C9480C.bin"

	.align 2
DirectSoundWaveData_08C954E8::
	.incbin "sound/direct_sound_samples/08C954E8.bin"

	.align 2
DirectSoundWaveData_08C970AC::
	.incbin "sound/direct_sound_samples/08C970AC.bin"

	.align 2
DirectSoundWaveData_08C98960::
	.incbin "sound/direct_sound_samples/08C98960.bin"

	.align 2
DirectSoundWaveData_08C98DA0::
	.incbin "sound/direct_sound_samples/08C98DA0.bin"

	.align 2
DirectSoundWaveData_08C9B2A4::
	.incbin "sound/direct_sound_samples/08C9B2A4.bin"

	.align 2
DirectSoundWaveData_08C9CE6C::
	.incbin "sound/direct_sound_samples/08C9CE6C.bin"

	.align 2
DirectSoundWaveData_08C9E850::
	.incbin "sound/direct_sound_samples/08C9E850.bin"

	.align 2
DirectSoundWaveData_08C9F830::
	.incbin "sound/direct_sound_samples/08C9F830.bin"

	.align 2
DirectSoundWaveData_08CA25E4::
	.incbin "sound/direct_sound_samples/08CA25E4.bin"

	.align 2
DirectSoundWaveData_08CA2888::
	.incbin "sound/direct_sound_samples/08CA2888.bin"

	.align 2
DirectSoundWaveData_08CA32EC::
	.incbin "sound/direct_sound_samples/08CA32EC.bin"

	.align 2
DirectSoundWaveData_08CA45D0::
	.incbin "sound/direct_sound_samples/08CA45D0.bin"

	.align 2
DirectSoundWaveData_08CA48C0::
	.incbin "sound/direct_sound_samples/08CA48C0.bin"

	.align 2
DirectSoundWaveData_08CAB0D0::
	.incbin "sound/direct_sound_samples/08CAB0D0.bin"

	.align 2
DirectSoundWaveData_08CABB48::
	.incbin "sound/direct_sound_samples/08CABB48.bin"

	.align 2
DirectSoundWaveData_08CAC754::
	.incbin "sound/direct_sound_samples/08CAC754.bin"

	.align 2
DirectSoundWaveData_08CB0168::
	.incbin "sound/direct_sound_samples/08CB0168.bin"

	.align 2
DirectSoundWaveData_08CB4938::
	.incbin "sound/direct_sound_samples/08CB4938.bin"

	.align 2
DirectSoundWaveData_08CB54F8::
	.incbin "sound/direct_sound_samples/08CB54F8.bin"

	.align 2
DirectSoundWaveData_08CB5BD0::
	.incbin "sound/direct_sound_samples/08CB5BD0.bin"

	.align 2
DirectSoundWaveData_08CB6E28::
	.incbin "sound/direct_sound_samples/08CB6E28.bin"

	.align 2
DirectSoundWaveData_08CB7EC0::
	.incbin "sound/direct_sound_samples/08CB7EC0.bin"

	.align 2
DirectSoundWaveData_08CBC080::
	.incbin "sound/direct_sound_samples/08CBC080.bin"

	.align 2
DirectSoundWaveData_08CBEB6C::
	.incbin "sound/direct_sound_samples/08CBEB6C.bin"

	.align 2
DirectSoundWaveData_08CBFD64::
	.incbin "sound/direct_sound_samples/08CBFD64.bin"

	.align 2
DirectSoundWaveData_08CC2278::
	.incbin "sound/direct_sound_samples/08CC2278.bin"

	.align 2
DirectSoundWaveData_08CC59AC::
	.incbin "sound/direct_sound_samples/08CC59AC.bin"

	.align 2
DirectSoundWaveData_08CC9180::
	.incbin "sound/direct_sound_samples/08CC9180.bin"

	.align 2
DirectSoundWaveData_08CCAF54::
	.incbin "sound/direct_sound_samples/08CCAF54.bin"

	.align 2
DirectSoundWaveData_08CCB840::
	.incbin "sound/direct_sound_samples/08CCB840.bin"

	.align 2
DirectSoundWaveData_08CCE6F8::
	.incbin "sound/direct_sound_samples/08CCE6F8.bin"

	.align 2
DirectSoundWaveData_08CD12BC::
	.incbin "sound/direct_sound_samples/08CD12BC.bin"

	.align 2
DirectSoundWaveData_08CD3CB0::
	.incbin "sound/direct_sound_samples/08CD3CB0.bin"

	.align 2
DirectSoundWaveData_08CD49CC::
	.incbin "sound/direct_sound_samples/08CD49CC.bin"

	.align 2
DirectSoundWaveData_08CD76E4::
	.incbin "sound/direct_sound_samples/08CD76E4.bin"

	.align 2
DirectSoundWaveData_08CD8E2C::
	.incbin "sound/direct_sound_samples/08CD8E2C.bin"

	.align 2
DirectSoundWaveData_08CDA5C8::
	.incbin "sound/direct_sound_samples/08CDA5C8.bin"

	.align 2
DirectSoundWaveData_08CDC4B4::
	.incbin "sound/direct_sound_samples/08CDC4B4.bin"

	.align 2
DirectSoundWaveData_08CDDE18::
	.incbin "sound/direct_sound_samples/08CDDE18.bin"

	.align 2
DirectSoundWaveData_08CDE6D8::
	.incbin "sound/direct_sound_samples/08CDE6D8.bin"

	.align 2
DirectSoundWaveData_08CE3730::
	.incbin "sound/direct_sound_samples/08CE3730.bin"

	.align 2
DirectSoundWaveData_08CE43E8::
	.incbin "sound/direct_sound_samples/08CE43E8.bin"

	.align 2
DirectSoundWaveData_08CE52B0::
	.incbin "sound/direct_sound_samples/08CE52B0.bin"

	.align 2
DirectSoundWaveData_08CE60B4::
	.incbin "sound/direct_sound_samples/08CE60B4.bin"

	.align 2
DirectSoundWaveData_08CE7718::
	.incbin "sound/direct_sound_samples/08CE7718.bin"

	.align 2
DirectSoundWaveData_08CE824C::
	.incbin "sound/direct_sound_samples/08CE824C.bin"

	.align 2
DirectSoundWaveData_08CE95E0::
	.incbin "sound/direct_sound_samples/08CE95E0.bin"

	.align 2
DirectSoundWaveData_08CE9868::
	.incbin "sound/direct_sound_samples/08CE9868.bin"

	.align 2
DirectSoundWaveData_08CEB4FC::
	.incbin "sound/direct_sound_samples/08CEB4FC.bin"

	.align 2
DirectSoundWaveData_08CECB08::
	.incbin "sound/direct_sound_samples/08CECB08.bin"

	.align 2
DirectSoundWaveData_08CEE2CC::
	.incbin "sound/direct_sound_samples/08CEE2CC.bin"

	.align 2
DirectSoundWaveData_08CEF760::
	.incbin "sound/direct_sound_samples/08CEF760.bin"

	.align 2
DirectSoundWaveData_08CF0F20::
	.incbin "sound/direct_sound_samples/08CF0F20.bin"

	.align 2
DirectSoundWaveData_08CF2650::
	.incbin "sound/direct_sound_samples/08CF2650.bin"

	.align 2
DirectSoundWaveData_08CF3670::
	.incbin "sound/direct_sound_samples/08CF3670.bin"

	.align 2
DirectSoundWaveData_08CF48E8::
	.incbin "sound/direct_sound_samples/08CF48E8.bin"

	.align 2
DirectSoundWaveData_08CF58B8::
	.incbin "sound/direct_sound_samples/08CF58B8.bin"

	.align 2
DirectSoundWaveData_08CF5E5C::
	.incbin "sound/direct_sound_samples/08CF5E5C.bin"

	.align 2
DirectSoundWaveData_08CF7864::
	.incbin "sound/direct_sound_samples/08CF7864.bin"

	.align 2
DirectSoundWaveData_08CF877C::
	.incbin "sound/direct_sound_samples/08CF877C.bin"

	.align 2
DirectSoundWaveData_08CF9340::
	.incbin "sound/direct_sound_samples/08CF9340.bin"

	.align 2
DirectSoundWaveData_08CFA6E4::
	.incbin "sound/direct_sound_samples/08CFA6E4.bin"

	.align 2
DirectSoundWaveData_08CFAC00::
	.incbin "sound/direct_sound_samples/08CFAC00.bin"

	.align 2
DirectSoundWaveData_08CFB4FC::
	.incbin "sound/direct_sound_samples/08CFB4FC.bin"

	.align 2
DirectSoundWaveData_08CFBECC::
	.incbin "sound/direct_sound_samples/08CFBECC.bin"

	.align 2
DirectSoundWaveData_08CFD22C::
	.incbin "sound/direct_sound_samples/08CFD22C.bin"

	.align 2
DirectSoundWaveData_08CFE1FC::
	.incbin "sound/direct_sound_samples/08CFE1FC.bin"

	.align 2
DirectSoundWaveData_08CFFE40::
	.incbin "sound/direct_sound_samples/08CFFE40.bin"

	.align 2
DirectSoundWaveData_08D03AF4::
	.incbin "sound/direct_sound_samples/08D03AF4.bin"

	.align 2
DirectSoundWaveData_08D05064::
	.incbin "sound/direct_sound_samples/08D05064.bin"

	.align 2
DirectSoundWaveData_08D0A138::
	.incbin "sound/direct_sound_samples/08D0A138.bin"

	.align 2
DirectSoundWaveData_08D0FD4C::
	.incbin "sound/direct_sound_samples/08D0FD4C.bin"

	.align 2
DirectSoundWaveData_08D11F80::
	.incbin "sound/direct_sound_samples/08D11F80.bin"

	.align 2
DirectSoundWaveData_08D16D20::
	.incbin "sound/direct_sound_samples/08D16D20.bin"

	.align 2
DirectSoundWaveData_08D20698::
	.incbin "sound/direct_sound_samples/08D20698.bin"

	.align 2
DirectSoundWaveData_08D2390C::
	.incbin "sound/direct_sound_samples/08D2390C.bin"

	.align 2
DirectSoundWaveData_08D24594::
	.incbin "sound/direct_sound_samples/08D24594.bin"

	.align 2
DirectSoundWaveData_08D25F28::
	.incbin "sound/direct_sound_samples/08D25F28.bin"

	.align 2
DirectSoundWaveData_08D2D07C::
	.incbin "sound/direct_sound_samples/08D2D07C.bin"

	.align 2
DirectSoundWaveData_08D2D84C::
	.incbin "sound/direct_sound_samples/08D2D84C.bin"

	.align 2
DirectSoundWaveData_08D2F338::
	.incbin "sound/direct_sound_samples/08D2F338.bin"

	.align 2
DirectSoundWaveData_08D3178C::
	.incbin "sound/direct_sound_samples/08D3178C.bin"

	.align 2
DirectSoundWaveData_08D34180::
	.incbin "sound/direct_sound_samples/08D34180.bin"

	.align 2
DirectSoundWaveData_08D361D4::
	.incbin "sound/direct_sound_samples/08D361D4.bin"

	.align 2
DirectSoundWaveData_08D390D8::
	.incbin "sound/direct_sound_samples/08D390D8.bin"

	.align 2
DirectSoundWaveData_08D3A79C::
	.incbin "sound/direct_sound_samples/08D3A79C.bin"

	.align 2
DirectSoundWaveData_08D3D20C::
	.incbin "sound/direct_sound_samples/08D3D20C.bin"

	.align 2
DirectSoundWaveData_08D3FC80::
	.incbin "sound/direct_sound_samples/08D3FC80.bin"
