	.align 4
ProgrammableWaveData_08B59E00::
	.incbin "sound/programmable_wave_samples/08B59E00.pcm"

	.align 4
ProgrammableWaveData_08B59E10::
	.incbin "sound/programmable_wave_samples/08B59E10.pcm"

	.align 4
ProgrammableWaveData_08B59E20::
	.incbin "sound/programmable_wave_samples/08B59E20.pcm"

	.align 4
ProgrammableWaveData_08B59E30::
	.incbin "sound/programmable_wave_samples/08B59E30.pcm"

	.align 4
ProgrammableWaveData_08B59E40::
	.incbin "sound/programmable_wave_samples/08B59E40.pcm"
