	.align 2
ProgrammableWaveData_08B59D70:: @ unused
	.incbin "sound/programmable_wave_samples/08B59D70.pcm"

	.align 2
ProgrammableWaveData_08B59D80:: @ unused
	.incbin "sound/programmable_wave_samples/08B59D80.pcm"

	.align 2
ProgrammableWaveData_08B59D90:: @ unused
	.incbin "sound/programmable_wave_samples/08B59D90.pcm"

	.align 2
ProgrammableWaveData_08B59DA0:: @ unused
	.incbin "sound/programmable_wave_samples/08B59DA0.pcm"

	.align 2
ProgrammableWaveData_08B59DB0:: @ unused
	.incbin "sound/programmable_wave_samples/08B59DB0.pcm"

	.align 2
ProgrammableWaveData_08B59DC0:: @ unused
	.incbin "sound/programmable_wave_samples/08B59DC0.pcm"

	.align 2
ProgrammableWaveData_08B59DD0:: @ unused
	.incbin "sound/programmable_wave_samples/08B59DD0.pcm"

	.align 2
ProgrammableWaveData_08B59DE0:: @ unused
	.incbin "sound/programmable_wave_samples/08B59DE0.pcm"

	.align 2
ProgrammableWaveData_08B59DF0:: @ unused
	.incbin "sound/programmable_wave_samples/08B59DF0.pcm"

	.align 2
ProgrammableWaveData_08B59E00::
	.incbin "sound/programmable_wave_samples/08B59E00.pcm"

	.align 2
ProgrammableWaveData_08B59E10::
	.incbin "sound/programmable_wave_samples/08B59E10.pcm"

	.align 2
ProgrammableWaveData_08B59E20::
	.incbin "sound/programmable_wave_samples/08B59E20.pcm"

	.align 2
ProgrammableWaveData_08B59E30::
	.incbin "sound/programmable_wave_samples/08B59E30.pcm"

	.align 2
ProgrammableWaveData_08B59E40::
	.incbin "sound/programmable_wave_samples/08B59E40.pcm"

	.align 2
ProgrammableWaveData_08B59E50:: @ unused
	.incbin "sound/programmable_wave_samples/08B59E50.pcm"

	.align 2
ProgrammableWaveData_08B59E60:: @ unused
	.incbin "sound/programmable_wave_samples/08B59E60.pcm"

	.align 2
ProgrammableWaveData_08B59E70:: @ unused
	.incbin "sound/programmable_wave_samples/08B59E70.pcm"

	.align 2
ProgrammableWaveData_08B59E80:: @ unused
	.incbin "sound/programmable_wave_samples/08B59E80.pcm"

	.align 2
ProgrammableWaveData_08B59E90:: @ unused
	.incbin "sound/programmable_wave_samples/08B59E90.pcm"
