#ifndef GUARD_OBJECT_TYPES_H
#define GUARD_OBJECT_TYPES_H

#define OBJ_WADDLE_DEE_1               0x00
#define OBJ_BRONTO_BURT                0x01
#define OBJ_BLIPPER                    0x02
#define OBJ_GLUNK                      0x03
#define OBJ_SQUISHY                    0x04
#define OBJ_SCARFY                     0x05
#define OBJ_GORDO                      0x06
#define OBJ_SNOOTER_1                  0x07
#define OBJ_CHIP                       0x08
#define OBJ_SOARAR                     0x09
#define OBJ_HALEY                      0x0A
#define OBJ_ROLYPOLY                   0x0B
#define OBJ_CUPIE                      0x0C
#define OBJ_BLOCKIN                    0x0D
#define OBJ_SNOOTER_2                  0x0E
#define OBJ_LEAP                       0x0F
#define OBJ_JACK                       0x10
#define OBJ_BIG_WADDLE_DEE             0x11
#define OBJ_WADDLE_DOO                 0x12
#define OBJ_FLAMER                     0x13
#define OBJ_HOT_HEAD                   0x14
#define OBJ_LASER_BALL                 0x15
#define OBJ_PENGY                      0x16
#define OBJ_ROCKY                      0x17
#define OBJ_SIR_KIBBLE                 0x18
#define OBJ_SPARKY                     0x19
#define OBJ_SWORD_KNIGHT               0x1A
#define OBJ_UFO                        0x1B
#define OBJ_TWISTER                    0x1C
#define OBJ_WHEELIE                    0x1D
#define OBJ_NODDY                      0x1E
#define OBJ_GOLEM_1                    0x1F
#define OBJ_GOLEM_2                    0x20
#define OBJ_GOLEM_3                    0x21
#define OBJ_FOLEY_1                    0x22
#define OBJ_SHOOTY                     0x23
#define OBJ_SCARFY_FALLING             0x24
#define OBJ_BOXIN                      0x25
#define OBJ_COOKIN                     0x26
#define OBJ_MINNY                      0x27
#define OBJ_BOMBER                     0x28
#define OBJ_HEAVY_KNIGHT               0x29
#define OBJ_GIANT_ROCKY                0x2A
#define OBJ_METAL_GUARDIAN             0x2B
#define OBJ_EMPTY_2C                   0x2C
#define OBJ_BATTY                      0x2D
#define OBJ_FOLEY_2                    0x2E
#define OBJ_BANG_BANG                  0x2F
#define OBJ_DARK_MIND_BOMB             0x30
#define OBJ_EMPTY_31                   0x31
#define OBJ_DROPPY                     0x32
#define OBJ_PRANK                      0x33
#define OBJ_MIRRA                      0x34
#define OBJ_SHOTZO_1                   0x35
#define OBJ_SHADOW_KIRBY               0x36
#define OBJ_WADDLE_DEE_2               0x37
#define OBJ_MR_FLOSTY                  0x38
#define OBJ_BONKERS                    0x39
#define OBJ_PHAN_PHAN                  0x3A
#define OBJ_BATAFIRE                   0x3B
#define OBJ_BOX_BOXER                  0x3C
#define OBJ_BOXY                       0x3D
#define OBJ_MASTER_HAND                0x3E
#define OBJ_BOMBAR                     0x3F
#define OBJ_EMPTY_40                   0x40
#define OBJ_EMPTY_41                   0x41
#define OBJ_EMPTY_42                   0x42
#define OBJ_EMPTY_43                   0x43
#define OBJ_EMPTY_44                   0x44
#define OBJ_KRACKO                     0x45
#define OBJ_KING_GOLEM                 0x46
#define OBJ_CRAZY_HAND_1               0x47
#define OBJ_GOBBLER                    0x48
#define OBJ_WIZ                        0x49
#define OBJ_MOLEY                      0x4A
#define OBJ_MEGA_TITAN                 0x4B
#define OBJ_TITAN_HEAD                 0x4C
#define OBJ_CRAZY_HAND_2               0x4D
#define OBJ_DARK_META_KNIGHT           0x4E
#define OBJ_DARK_MIND_FORM_1           0x4F
#define OBJ_DARK_MIND_FORM_2           0x50
#define OBJ_DARK_MIND_FORM_3_TRIGGER   0x51
#define OBJ_DARK_META_KNIGHT_W8        0x52
#define OBJ_EMPTY_53                   0x53
#define OBJ_EMPTY_54                   0x54
#define OBJ_EMPTY_55                   0x55
#define OBJ_EMPTY_56                   0x56
#define OBJ_EMPTY_57                   0x57
#define OBJ_EMPTY_58                   0x58
#define OBJ_EMPTY_59                   0x59
#define OBJ_EMPTY_5A                   0x5A
#define OBJ_EMPTY_5B                   0x5B
#define OBJ_EMPTY_5C                   0x5C
#define OBJ_EMPTY_5D                   0x5D
#define OBJ_SMALL_FOOD                 0x5E
#define OBJ_POP_SODA                   0x5F
#define OBJ_MEAT                       0x60
#define OBJ_TOMATO                     0x61
#define OBJ_BATTERY                    0x62
#define OBJ_1UP                        0x63
#define OBJ_INVINCIBLE_CANDY           0x64
#define OBJ_MIRROR_SHARD               0x65
#define OBJ_EMPTY_66                   0x66
#define OBJ_EMPTY_67                   0x67
#define OBJ_EMPTY_68                   0x68
#define OBJ_UNKNOWN_69                 0x69
#define OBJ_EMPTY_6A                   0x6A
#define OBJ_EMPTY_6B                   0x6B
#define OBJ_EMPTY_6C                   0x6C
#define OBJ_SMALL_BUTTON               0x6D
#define OBJ_FLAME                      0x6E
#define OBJ_BARRED_DOOR                0x6F
#define OBJ_SHOTZO_2                   0x70
#define OBJ_BUTTON_DOOR                0x71
#define OBJ_BOSS_CHALLENGE_DOOR        0x72
#define OBJ_UNKNOWN_73                 0x73
#define OBJ_UNKNOWN_74                 0x74
#define OBJ_UNKNOWN_75                 0x75
#define OBJ_UNKNOWN_76                 0x76
#define OBJ_UNKNOWN_77                 0x77
#define OBJ_UNKNOWN_78                 0x78
#define OBJ_FALLING_STONE_BLOCK        0x79
#define OBJ_UNKNOWN_7A                 0x7A
#define OBJ_STAR_PLATFORM              0x7B
#define OBJ_SMALL_FLAME                0x7C
#define OBJ_FALLING_BIG_STONE_BLOCK    0x7D
#define OBJ_BIG_STONE_BLOCK_INHALE     0x7E
#define OBJ_UNKNOWN_7F                 0x7F
#define OBJ_SMALL_CHEST                0x80
#define OBJ_BIG_CHEST                  0x81
#define OBJ_UNKNOWN_82                 0x82
#define OBJ_UNKNOWN_83                 0x83
#define OBJ_WARP_STAR                  0x84
#define OBJ_GOAL_STAR                  0x85
#define OBJ_BIG_BUTTON                 0x86
#define OBJ_UNKNOWN_87                 0x87
#define OBJ_BIG_STONE_BLOCK_IMPACT     0x88
#define OBJ_BIG_STONE_BLOCK_BOTH       0x89
#define OBJ_CANNON                     0x8A
#define OBJ_8_DIR_CANNON               0x8B
#define OBJ_UNKNOWN_8C                 0x8C
#define OBJ_UNKNOWN_8D                 0x8D
#define OBJ_CUTSCENE_TRIGGER           0x8E
#define OBJ_MASTER_SWORD_UNOBTAINABLE  0x8F
#define OBJ_WIND_EFFECT                0x90
#define OBJ_UNKNOWN_91                 0x91
#define OBJ_ABILITY_STATUE_1           0x92
#define OBJ_ABILITY_STATUE_2           0x93
#define OBJ_ABILITY_STATUE_3           0x94
#define OBJ_ABILITY_STATUE_4           0x95
#define OBJ_ABILITY_STATUE_RANDOM      0x96
#define OBJ_UNKNOWN_97                 0x97
#define OBJ_MASTER_SWORD_STAND         0x98
#define OBJ_UNKNOWN_99                 0x99
#define OBJ_EMPTY_9A                   0x9A
#define OBJ_KING_GOLEM_ROCK            0x9B
#define OBJ_KING_GOLEM_GORDO           0x9C
#define OBJ_FOLEY_LEAVES               0x9D
#define OBJ_COOKIN_PAN_1               0x9E
#define OBJ_UNKNOWN_9F                 0x9F
#define OBJ_GOBBLER_BABY               0xA0
#define OBJ_THROWN_FLAME               0xA1
#define OBJ_UNKNOWN_A2                 0xA2
#define OBJ_ABILITY_STAR_1             0xA3
#define OBJ_ABILITY_STAR_2             0xA4
#define OBJ_STAR_INHALABLE             0xA5
#define OBJ_ENEMY_EXPLOSION_1          0xA6
#define OBJ_ENEMY_EXPLOSION_2          0xA7
#define OBJ_BONKERS_NUT_SMALL          0xA8
#define OBJ_BONERS_NUT_LARGE           0xA9
#define OBJ_APPLE                      0xAA
#define OBJ_FIRE_PARTICLE              0xAB
#define OBJ_ICE_PARTICLE               0xAC
#define OBJ_THROWN_BOMB                0xAD
#define OBJ_COOKIN_PAN_2               0xAE
#define OBJ_BANANA_PEEL                0xAF
#define OBJ_BOXY_BOX                   0xB0
#define OBJ_SHOOTING_ENEMY_STAR        0xB1
#define OBJ_BOMAR_BOMB                 0xB2
#define OBJ_BOMAR_MISSILE              0xB3
#define OBJ_BOX_BOXER_ENERGY_BALL      0xB4
#define OBJ_WIZ_FOOTBALL               0xB5
#define OBJ_WIZ_CAR                    0xB6
#define OBJ_WIZ_BALLOON                0xB7
#define OBJ_WIZ_BOMB                   0xB8
#define OBJ_WIZ_CLOUD                  0xB9
#define OBJ_WIZ_APPE                   0xBA
#define OBJ_WIZ_DROPPY                 0xBB
#define OBJ_TITAN_ARM_1                0xBC
#define OBJ_TITAN_ARM_2                0xBD
#define OBJ_TITAN_ARM_3                0xBE
#define OBJ_TITAN_ARM_4                0xBF
#define OBJ_TITAN_HEAD_MISSILE         0xC0
#define OBJ_MOLEY_ROCK                 0xC1
#define OBJ_MOLEY_SCREW                0xC2
#define OBJ_MOLEY_TIRE                 0xC3
#define OBJ_MOLEY_BOMB                 0xC4
#define OBJ_MOLEY_BIG_ROCK             0xC5
#define OBJ_MOLEY_BARREL               0xC6
#define OBJ_MOLEY_SPIKE_BALL           0xC7
#define OBJ_MASTER_HAND_BULLET         0xC8
#define OBJ_THROWN_BOMB_2              0xC9
#define OBJ_UNKNOWN_CA                 0xCA
#define OBJ_DARK_MIND_STAR_FIRE        0xCB
#define OBJ_DARK_MIND_STAR_ICE         0xCC
#define OBJ_DARK_MIND_STAR_SPARK       0xCD
#define OBJ_DARK_MIND_STAR_MIX         0xCE
#define OBJ_UNKNOWN_CF                 0xCF
#define OBJ_UNKNOWN_D0                 0xD0
#define OBJ_DARK_MIND_LASER            0xD1
#define OBJ_DARK_MIND_LASER_SHOWER     0xD2
#define OBJ_DARK_MIND_MIRROR_CUTTER    0xD3
#define OBJ_UNKNOWN_D4                 0xD4
#define OBJ_SIR_KIBBLE_CUTTER          0xD5
#define OBJ_SHOTZO_SFX                 0xD6
#define OBJ_SHOTZO_BULLET              0xD7
#define OBJ_CUPIE_ARROW                0xD8
#define OBJ_JACK_STAR                  0xD9
#define OBJ_SHOOTY_BOMB                0xDA
#define OBJ_UNKNOWN_DB                 0xDB

#endif // GUARD_OBJECT_TYPES_H
