#ifndef GUARD_CONSTANTS_PAUSE_MENU_H
#define GUARD_CONSTANTS_PAUSE_MENU_H

/*
 * Enumerates doors on the world map and is used as index into arrays.
 * Must thus remain contiguous.
 */
enum WorldMapDoor {
    WORLDMAP_NO_UNLOCK,
    WORLDMAP_MOONLIGHT_MANSION,
    WORLDMAP_RAINBOW_ROUTE_EAST,
    WORLDMAP_RAINBOW_ROUTE_SOUTH,
    WORLDMAP_CABBAGE_CAVERN_CENTER,
    WORLDMAP_RAINBOW_ROUTE_WEST,
    WORLDMAP_CARROT_CASTLE,
    WORLDMAP_RAINBOW_ROUTE_NORTH,
    WORLDMAP_MUSTARD_MOUNTAIN,
    WORLDMAP_CABBAGE_CAVERN_WEST,
    WORLDMAP_RADISH_RUINS,
    WORLDMAP_PEPPERMINT_PALACE_EAST,
    WORLDMAP_PEPPERMINT_PALACE_WEST,
    WORLDMAP_CABBAGE_CAVERN_EAST,
    WORLDMAP_OLIVE_OCEAN,
    WORLDMAP_CANDY_CONSTELLATION,
    NUM_WORLDMAP_DOORS,
};

enum PauseMenuId {
    MENU_HELP = 1,
    MENU_WORLDMAP = 2,
    MENU_AREAMAP = 4,
};

enum AreaId {
    AREA_TUTORIAL,
    AREA_RAINBOW_ROUTE,
    AREA_MOONLIGHT_MANSION,
    AREA_CABBAGE_CAVERN,
    AREA_MUSTARD_MOUNTAIN,
    AREA_CARROT_CASTLE,
    AREA_OLIVE_OCEAN,
    AREA_PEPPERMINT_PALACE,
    AREA_RADISH_RUINS,
    AREA_CANDY_CONSTELLATION,
    AREA_DIMENSION_MIRROR,
    NUM_AREA_IDS,
};

#endif
