#ifndef GUARD_CONSTANTS_PAUSE_MENU_H
#define GUARD_CONSTANTS_PAUSE_MENU_H

#define WORLDMAP_NO_UNLOCK              0x0
#define WORLDMAP_MOONLIGHT_MANSION      0x1
#define WORLDMAP_RAINBOW_ROUTE_EAST     0x2
#define WORLDMAP_RAINBOW_ROUTE_SOUTH    0x3
#define WORLDMAP_CABBAGE_CAVERN_CENTER  0x4
#define WORLDMAP_RAINBOW_ROUTE_WEST     0x5
#define WORLDMAP_CARROT_CASTLE          0x6
#define WORLDMAP_RAINBOW_ROUTE_NORTH    0x7
#define WORLDMAP_MUSTARD_MOUNTAIN       0x8
#define WORLDMAP_CABBAGE_CAVERN_WEST    0x9
#define WORLDMAP_RADISH_RUINS           0xA
#define WORLDMAP_PEPPERMINT_PALACE_EAST 0xB
#define WORLDMAP_PEPPERMINT_PALACE_WEST 0xC
#define WORLDMAP_CABBAGE_CAVERN_EAST    0xD
#define WORLDMAP_OLIVE_OCEAN            0xE
#define WORLDMAP_CANDY_CONSTELLATION    0xF
#define NUM_WORLDMAP_DOORS              0x10

#endif
